language: node_js
node_js: '13'
dist: bionic
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '13'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'X/mNYy9BfLNw9pOtbPyWHfH1Ttm0ouAqHM9PL+YwQpp0KT3qTBQq3EuwQLECLaCjU1MTaaFSg5+4FIc6+pEvd7qPv7/6fnze5idHGbfWwmcYBySmbpflNxQEVo/neED9y4SSOybr5la9q/8mT+soOwgI/hJYBmu+YKNaDgQYBLnVAVrW8JB8Q91rgOJy63MMJK6hnQkXW0WL8wh0pFojF8zVBseuHK4Zt92bjd7bQpTF8mdvpzNtCxRkmbMTRpeL2ouob5BLHYQsS/bvGiDmlS6SSM1FTv9mnU1MpUhYFdTqEn1nMYtcQPLDXB80CYm3+ntYegWh9X8Gt7NHa7s83+CRYAKhaOQKH+hh1lpRgyBS8r+B1AN7nsmHnOmdlYxtRNMGJg8sUck68lZbdR68FMiovjSMyvUBm5Xr29Y9l2D23vcfQaehVjO57Vtmg8vgv30HL6io635CbqkH7lN/M6atLeRJDrF+ltvSlBitXeCLoSzQeC2ctt9N/LaYUY+GAtDKoehl2UVekv3kePAK+ZBk8K0Rj3uauHd6+TS0BQKaLEqY/n+psRXlplg9jUm0nPWZsqRDxWlfjVNYA0d8nuc8xGgxoUozisMLzU0pcxmzJ8yryH0BNFATDyMnkD4bFJhKNG0BcaW2Vfn/4Oo9YlAYAUOA8FAj2CwRI5/aIRo='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
